/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaLog */

#ifndef _Included_JavaLog
#define _Included_JavaLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaLog
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JavaLog_log
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
