/* DO NOT EDIT THIS FILE - it is machine generated */
#include "/System/Library/Frameworks/JavaVM.framework/Versions/1.4.1/Headers/jni.h"
/* Header for class JNITest */
#include <stdio.h>
#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
